In [2]:
#==============================================================================
# First step to write the python program is to take benefit out of libraries
# already available. We will only focus on the data science related libraries.
#==============================================================================

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd



In [4]:
#==============================================================================
# #import data from the data file. In our case its Health.csv. 
#==============================================================================


healthData = pd.read_csv ('C://Users//Sudipta//Desktop//ML//cellstrat//assignment//datasets//Health.csv')
healthData.head(100)

Ethnicity  Height (CM)  Weight (Kg) Will survive till 70
0     White        186.0         90.0                  Yes
1   African        185.0         98.0                   No
2     White        175.0         80.0                   No
3     White        180.0         88.0                  Yes
4     Asian        178.0          NaN                   No
5     Asian        172.0         72.0                  Yes
6   African        178.0         75.0                   No
7     White          NaN         89.0                  Yes
8   African        186.0         90.0                  Yes

In [5]:
#==============================================================================
# All mathematical operations will be performed on the matrix, so now we create
# matrix for dependent variables and independent variables.
#==============================================================================


X = healthData.iloc [:,:-1].values
y = healthData.iloc [:,3].values

X

array([['White', 186.0, 90.0],
       ['African', 185.0, 98.0],
       ['White', 175.0, 80.0],
       ['White', 180.0, 88.0],
       ['Asian', 178.0, nan],
       ['Asian', 172.0, 72.0],
       ['African', 178.0, 75.0],
       ['White', nan, 89.0],
       ['African', 186.0, 90.0]], dtype=object)

In [6]:
y

array(['Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes'], dtype=object)

In [7]:
#==============================================================================
# Handle the missing values, we can see that in dataset there are some missing
# values, we will use strategy to impute mean of column values in these places
#==============================================================================

from sklearn.preprocessing import Imputer
# First create an Imputer
missingValueImputer = Imputer (missing_values = 'NaN', strategy = 'median',
                               axis = 0)
# Set which columns imputer should perform
missingValueImputer = missingValueImputer.fit (X[:,1:3])
# update values of X with new values
X[:,1:3] = missingValueImputer.transform(X[:,1:3])

print(X)

[['White' 186.0 90.0]
 ['African' 185.0 98.0]
 ['White' 175.0 80.0]
 ['White' 180.0 88.0]
 ['Asian' 178.0 88.5]
 ['Asian' 172.0 72.0]
 ['African' 178.0 75.0]
 ['White' 179.0 89.0]
 ['African' 186.0 90.0]]


In [9]:
#==============================================================================
# Encode the categorial data. So now instead of character values we will have
# corresponding numerical values
#==============================================================================

from sklearn.preprocessing import LabelEncoder
X_labelencoder = LabelEncoder()
X[:, 0] = X_labelencoder.fit_transform(X[:, 0])
print (X)

[[2 186.0 90.0]
 [0 185.0 98.0]
 [2 175.0 80.0]
 [2 180.0 88.0]
 [1 178.0 88.5]
 [1 172.0 72.0]
 [0 178.0 75.0]
 [2 179.0 89.0]
 [0 186.0 90.0]]


In [10]:
# for y
y_labelencoder = LabelEncoder ()
y = y_labelencoder.fit_transform (y)
print (y)

[1 0 0 1 0 1 0 1 1]


In [11]:
#==============================================================================
# Implementing OneHotEncoder to separate category variables into dummy 
# variables.
#==============================================================================

from sklearn.preprocessing import OneHotEncoder
X_onehotencoder = OneHotEncoder (categorical_features = [0])
X = X_onehotencoder.fit_transform(X).toarray()
print (X)

[[   0.     0.     1.   186.    90. ]
 [   1.     0.     0.   185.    98. ]
 [   0.     0.     1.   175.    80. ]
 [   0.     0.     1.   180.    88. ]
 [   0.     1.     0.   178.    88.5]
 [   0.     1.     0.   172.    72. ]
 [   1.     0.     0.   178.    75. ]
 [   0.     0.     1.   179.    89. ]
 [   1.     0.     0.   186.    90. ]]


In [12]:
#==============================================================================
# split the dataset into training and test set. We will use 80/20 approach
#==============================================================================

from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split (X, y, test_size = 0.2,
                                                     random_state = 0)

In [13]:
#==============================================================================
# Feature scaling is to bring all the independent variables in a dataset into
# same scale, to avoid any variable dominating  the model. Here we will not 
# transform the dependent variables.
#==============================================================================

from sklearn.preprocessing import StandardScaler
independent_scalar = StandardScaler()
X_train = independent_scalar.fit_transform (X_train) #fit and transform
X_test = independent_scalar.transform (X_test) # only transform
print(X_train)

[[ 1.15470054 -0.63245553 -0.63245553  0.88159065  1.42374171]
 [-0.8660254   1.58113883 -0.63245553 -0.55834074  0.30328226]
 [ 1.15470054 -0.63245553 -0.63245553  1.08729513  0.48019691]
 [ 1.15470054 -0.63245553 -0.63245553 -0.55834074 -1.28894959]
 [-0.8660254  -0.63245553  1.58113883 -0.14693177  0.24431071]
 [-0.8660254  -0.63245553  1.58113883  1.08729513  0.48019691]
 [-0.8660254   1.58113883 -0.63245553 -1.79256765 -1.6427789 ]]
